### PR TITLE
Added support for ol@5.3.3

### PR DESCRIPTION
**Pull request by rpFilipe**
Hi @ghettovoice , I saw that you opened an issue #2  for adding support for ol v5 but never got around to implement it. I've made the alterations, tested and everything seems to be working.

### CODE REVIEW

**Comment by ghettovoice** [comment]
Great! 
I totally forget about this issue :man_facepalming: 
Thank you.

**Comment by rpFilipe** [comment]
Do you have a ETA to when you are going to release the new version?

**Comment by ghettovoice** [comment]
Already released

**Comment by rpFilipe** [comment]
Ohh, ok. Thanks
Does this automatically publish a new version in npm?

**Comment by rpFilipe** [comment]
Thanks  :)

**Pull request merged**
